---
name: Tree
version: 1.00
author: ~
abstract: an N-ary tree
license: perl
requires:
  Scalar::Util: 1.10
  perl: 5.6.0
build_requires:
  Scalar::Util: 1.10
  Test::Deep: 0.088
  Test::Exception: 0.15
  Test::More: 0.47
  Test::Warn: 0.08
provides:
  Tree:
    file: lib/Tree.pm
    version: 1.00
  Tree::Binary:
    file: lib/Tree/Binary.pm
    version: 1.00
  Tree::Fast:
    file: lib/Tree/Fast.pm
    version: 1.00
  Tree::Null:
    file: lib/Tree/Fast.pm
    version: ~
generated_by: Module::Build version 0.2701
